#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "omniai/anthropic"

client = OmniAI::Anthropic::Client.new

puts "> [USER] Tell me a joke"

response = client.chat("Tell me a joke")
puts response.text
